// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5hiKzCGnvOAWGvKFA5htxid-4RtIifg',
    appId: '1:561570645388:web:3559b433876f9ea77a42a9',
    messagingSenderId: '561570645388',
    projectId: 'my-love-biliran',
    authDomain: 'my-love-biliran.firebaseapp.com',
    storageBucket: 'my-love-biliran.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtG8NRfjwggFRaVkDS0hVq4EIiwYSIVs',
    appId: '1:561570645388:android:34f904a2bae369797a42a9',
    messagingSenderId: '561570645388',
    projectId: 'my-love-biliran',
    storageBucket: 'my-love-biliran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvz1IeCexNKOpqdlzJ8nLqhp3xwA38cE',
    appId: '1:561570645388:ios:af22a75b7cf0f2a17a42a9',
    messagingSenderId: '561570645388',
    projectId: 'my-love-biliran',
    storageBucket: 'my-love-biliran.firebasestorage.app',
    iosBundleId: 'com.example.loveBiliran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvz1IeCexNKOpqdlzJ8nLqhp3xwA38cE',
    appId: '1:561570645388:ios:af22a75b7cf0f2a17a42a9',
    messagingSenderId: '561570645388',
    projectId: 'my-love-biliran',
    storageBucket: 'my-love-biliran.firebasestorage.app',
    iosBundleId: 'com.example.loveBiliran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE5hiKzCGnvOAWGvKFA5htxid-4RtIifg',
    appId: '1:561570645388:web:0cff9a7adc59bc9f7a42a9',
    messagingSenderId: '561570645388',
    projectId: 'my-love-biliran',
    authDomain: 'my-love-biliran.firebaseapp.com',
    storageBucket: 'my-love-biliran.firebasestorage.app',
  );
}
